development:
  adapter: postgresql
  encoding: unicode
  database: gymnasia_development
  host: localhost
  pool: 5
  username: dave
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: gymnasia_test
  host: localhost
  pool: 5
  username: dave
  password:


production:
  adapter: postgresql
  encoding: unicode
  database: gymnasia_production
  pool: 5
  username: vagrant
  password: vagrant